version: '3.8'

services:
  flats-pooler:
    image: daniilsfirgers/flats-parser:development
    volumes:
      - ./config.toml:/app/config.toml 
      - ./flats.json:/app/flats.json  
    command: python3.10 -u /app/scraper/main.py