version: '3.8'

services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile  
    volumes:
      - ./config.toml:/app/config.toml 
      - ./flats.json:/app/flats.json  
    command: python3.10 /app/scraper/main.py