FROM python:alpine 

RUN apk update && apk add --no-cache vips-dev

WORKDIR /app

COPY requirements.scraper.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY scraper /app/scraper

ENV PYTHONPATH="/app"