FROM python:alpine

WORKDIR /app

# Copy the packages directory first
COPY packages ./packages

COPY requirements.backend.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY backend /app/backend

EXPOSE 8000

ENV PYTHONPATH=/app:/app/packages

# Start FastAPI with hot reload enabled
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
