version: '3.8'

services:
  flats-pooler:
    container_name: flats-pooler
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config.toml:/app/config.toml 
      - ./flats.json:/app/flats.json  
    command: python3.10 -u /app/scraper/main.py
    networks:
      - flats-pooler

  postgres:
    image: postgis/postgis:13-3.3 
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d flats"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: flats
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - flats-pooler
    
networks:
  flats-pooler:
    driver: bridge

volumes:
  postgres_data: