FROM python:3.10

WORKDIR /backend

COPY requirements.backend.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY backend /backend/dzivoklitis

EXPOSE 8000

ENV PYTHONPATH=/backend

# Start FastAPI with hot reload enabled
CMD ["uvicorn", "dzivoklitis.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
