FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    libvips-dev \
    && rm -rf /var/lib/apt/lists/*  # Clean up to reduce image size

WORKDIR /app

COPY requirements.scraper.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY scraper /app/scraper

ENV PYTHONPATH="/app"
ENV PYTHONUNBUFFERED=1
