name = "Flats web scraper"
version = "2.0.2"

[parsers]
[parsers.ss]
city_name = "riga" 
deal_type = "P훮rdod" # sell / hand_over (rent)
name = "ss" 
timeframe = "today-2" # today / today-2 / today-5

[parsers.city24]
city_code = "245396" 
deal_type = "P훮rdod" # sale / rent
name = "city24" 

[parsers.pp]
city_code = "85" 
deal_type = "P훮rdod" # 1 / 5
name = "pp" 

[parsers.varianti]
city_code = "50" 
deal_type = "P훮rdod" # sell / rent
name = "varianti" 

[telegram]
sleep_time = 0.5 # 500ms
